server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  dataSource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./app;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

environment:
  properties:
    usertoken:
      secret: prodTest11231232Token