server:
  port: 8282
spring:
  jpa:
    hibernate:
      ddl-auto: update
  dataSource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./app
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG